### PR TITLE
Add ratings to cards

### PR DESCRIPTION
**Pull request by adgad**
/cc @matthew-andrews @keirog @tom-parker

### CODE REVIEW

**Comment by matthew-andrews** [comment]
:+1: from me …… but probably best to get a second opinion

**Comment by tom-parker** [comment]
My only question is did this come via design? And do we need to show a relevant state in the demos for styleguide?

**Comment by adgad** [comment]
I've run it past @simonwilliamsFT - I reckon let's show people at the next demo and if we think it's a worthwhile addition then I can add a styleguide demo

**Comment by adgad** [comment]
(the property will only be on dobi behind a flag for the time being)

**Pull request merged**
