### PR TITLE
allow multiple primary tags

### PR DESCRIPTION
**Pull request by wheresrhys**
I don't think the component should know anything about where the tags come from (keeping `followedTags` in for backward compatibility, but remove when renaming to `n-*`)

@adgad @tom-parker @keirog

### CODE REVIEW

**Comment by tom-parker** [comment]
Sounds good. Is multiple tags used in myFT? Just wondering if design know that multiple tags is a scenario that can happen

**Comment by keirog** [comment]
Good point on design knowing. :+1: if they're ok with it

**Comment by wheresrhys** [comment]
This doesn't actually introduce anything new visually - cards on myft already have more than one tag (which design should be aware of as a requirement). This just tidies up the implementation a little

**Comment by keirog** [comment]
Fair enough, :+1:

**Pull request merged**
